In [1]:
import numpy as  np
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [2]:
a = np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
a = np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
aa = np.full((3,3),5)
aa

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [9]:
b = np.arange(1,10+1,2)
b

array([1, 3, 5, 7, 9])

In [14]:
c = np.linspace(0,1,10)
c


array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [15]:
aaa = np.random.rand(2,3)
aaa

array([[0.35435268, 0.59728378, 0.78116312],
       [0.81804734, 0.2665731 , 0.37515358]])

In [16]:
aa = np.random.randn(2,3)
aa

array([[ 0.40620446, -1.17138271,  0.42567769],
       [-0.20761652, -1.34958686,  2.26569001]])

In [20]:
aa = np.random.randint(1,100,5)
aa

array([63,  8, 18, 80, 15])

In [22]:
aa = np.diag([1,2,3,4]
             )
aa

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [23]:
array = np.array([1,2,3,4,5,6,7,8,9,10])
array



array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
n =array.size
n

10